// HelperTexts.swift: what the helper mode says, in pt-BR and en.
import Foundation

enum HelperTexts {
    static func t(_ k: String, lang: String) -> String { (lang == "en" ? en[k] : pt[k]) ?? k }
    static func t(_ k: String, _ a: String, lang: String) -> String { t(k, lang: lang).replacingOccurrences(of: "%@", with: a) }

    static let pt: [String: String] = [
        "menu": "Modo ajudante",
        "menu_on": "Ligado durante as gravações",
        "brain": "Cérebro: %@",
        "brain_local": "no Mac",
        "brain_cloud": "nuvem (sua chave)",
        "key_menu": "Chave da Anthropic…",
        "panel_menu": "Mostrar o painel",
        "panel_title": "Ipsio: ajudante",
        "status_idle": "Fica ativo quando uma gravação começa.",
        "status_listening": "Ouvindo. As dicas aparecem quando os outros terminam de falar.",
        "status_thinking": "Pensando numa dica…",
        "status_error": "Falha ao pedir dicas: %@. Tento de novo em instantes.",
        "why": "por quê",
        "hide": "ocultar",
        "source": "fonte: %@",
        "answers": "responde a: %@",
        "fm_os": "O cérebro no Mac exige macOS 26 com Apple Intelligence.",
        "fm_device": "Este Mac não tem Apple Intelligence (precisa de Apple silicon).",
        "fm_off": "Ative a Apple Intelligence em Ajustes do Sistema para usar o cérebro no Mac.",
        "fm_not_ready": "O modelo da Apple Intelligence ainda está sendo baixado. Tente mais tarde.",
        "fm_missing": "Esta versão do Ipsio não tem o cérebro no Mac.",
        "fm_other": "O cérebro no Mac não está disponível agora.",
        "cloud_offer": "Você pode usar a nuvem com a sua chave da Anthropic: Modo ajudante > Cérebro: nuvem.",
        "needs_key": "Falta a chave da Anthropic: Modo ajudante > Chave da Anthropic…",
        "needs_consent": "A nuvem só é usada depois que você concorda: escolha Cérebro: nuvem de novo.",
        "consent_title": "Usar a nuvem no modo ajudante?",
        "consent_body": "Durante a gravação, o TEXTO transcrito da reunião (não o áudio, não o vídeo) sai deste Mac para a Anthropic (api.anthropic.com), com a sua chave, para gerar as dicas e pesquisar na web os argumentos dos outros. Esse texto inclui as falas dos outros participantes, que podem não saber disso. A Anthropic trata esses dados pelas regras da API dela, e a sua chave paga o uso. Você pode voltar ao cérebro no Mac quando quiser.",
        "consent_ok": "Concordo, usar a nuvem",
        "cancel": "Cancelar",
        "key_title": "Chave da Anthropic",
        "key_body": "Cole a sua chave da API (começa com sk-ant-). Ela fica nas Chaves do macOS (Keychain), nunca no arquivo de configuração nem em log.",
        "key_save": "Salvar",
        "key_remove": "Apagar a chave",
        "key_saved": "Chave salva nas Chaves do macOS.",
        "key_removed": "Chave apagada.",
        "key_bad": "Isso não parece uma chave da Anthropic (começa com sk-ant-).",
        "key_failed": "Não consegui guardar a chave nas Chaves do macOS.",
        "no_live": "Transcrição ao vivo indisponível: %@. O modo ajudante não faz nada nesta gravação.",
        "unavailable_title": "Modo ajudante indisponível",
    ]

    static let en: [String: String] = [
        "menu": "Helper mode",
        "menu_on": "On during recordings",
        "brain": "Brain: %@",
        "brain_local": "on this Mac",
        "brain_cloud": "cloud (your key)",
        "key_menu": "Anthropic key…",
        "panel_menu": "Show the panel",
        "panel_title": "Ipsio: helper",
        "status_idle": "Turns on when a recording starts.",
        "status_listening": "Listening. Tips show up when the others finish speaking.",
        "status_thinking": "Thinking of a tip…",
        "status_error": "Asking for tips failed: %@. Trying again shortly.",
        "why": "why",
        "hide": "hide",
        "source": "source: %@",
        "answers": "answers: %@",
        "fm_os": "The on-Mac brain needs macOS 26 with Apple Intelligence.",
        "fm_device": "This Mac has no Apple Intelligence (it needs Apple silicon).",
        "fm_off": "Turn on Apple Intelligence in System Settings to use the on-Mac brain.",
        "fm_not_ready": "The Apple Intelligence model is still downloading. Try again later.",
        "fm_missing": "This build of Ipsio has no on-Mac brain.",
        "fm_other": "The on-Mac brain is not available right now.",
        "cloud_offer": "You can use the cloud with your own Anthropic key: Helper mode > Brain: cloud.",
        "needs_key": "The Anthropic key is missing: Helper mode > Anthropic key…",
        "needs_consent": "The cloud is used only after you agree: choose Brain: cloud again.",
        "consent_title": "Use the cloud in helper mode?",
        "consent_body": "While recording, the transcribed TEXT of the meeting (not the audio, not the video) leaves this Mac for Anthropic (api.anthropic.com), with your key, to make the tips and to search the web about the others' arguments. That text includes what the other participants say, and they may not know it. Anthropic handles this data under its API terms, and your key pays for the use. You can go back to the on-Mac brain at any time.",
        "consent_ok": "I agree, use the cloud",
        "cancel": "Cancel",
        "key_title": "Anthropic key",
        "key_body": "Paste your API key (it starts with sk-ant-). It is kept in the macOS Keychain, never in the settings file or a log.",
        "key_save": "Save",
        "key_remove": "Delete the key",
        "key_saved": "Key saved in the macOS Keychain.",
        "key_removed": "Key deleted.",
        "key_bad": "That does not look like an Anthropic key (it starts with sk-ant-).",
        "key_failed": "Could not keep the key in the macOS Keychain.",
        "no_live": "Live transcription unavailable: %@. Helper mode does nothing in this recording.",
        "unavailable_title": "Helper mode unavailable",
    ]
}
